# Generated by Django 5.0.1 on 2024-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="last_login_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
