# Generated by Django 5.0.1 on 2024-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_noteuser_last_login_attempt_noteuser_login_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
