# Generated by Django 5.0.1 on 2024-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_noteuser_blocked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="blocked_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
