# Generated by Django 5.0.1 on 2024-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("name", models.CharField(max_length=150, null=True)),
                ("password", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
